insert into banco(codigo, descricao)
values(341, 'Itaú Unibanco S.A');



INSERT INTO ARQUIVO_BANCARIO(ID,BANCO,CARTEIRA,DATA_ENVIO,DATA_GERACAO,GERADO_POR,NOME_ARQUIVO,QTD_LINHAS,TIPO,VALOR_TOTAL)  VALUES(1, 'SANTANDER',19,sysdate(),sysdate(),'RRCUNHA','CB1290809.RET',508,'RET',111233.98);









